name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Force fail if takes too long
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libespeak1
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest-xvfb
    
    - name: Run tests with virtual display
      run: |
        xvfb-run python -m pytest tests/ -v