name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk tk-dev libespeak1
        
    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      run: |
        pip install pywin32 comtypes
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with virtual display (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        export DISPLAY=:99.0
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        python -m pytest tests/ -v
    
    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m pytest tests/ -v